// Additional beginner questions. Keep prompts distinct: their hashes identify saved history.
export type BankEntry = [topic: string, question: string, answer: string, keywords: string[]];
export const extraQuestions: Record<string, BankEntry[]> = {
  Technical: [
    [
      'Databases',
      'What does a foreign key do in a relational database?',
      'A foreign key references a key in another table and maintains referential integrity between related rows.',
      ['referenc', 'table', 'integrity|relationship'],
    ],
    [
      'Databases',
      'How does a database index help a query, and what is one cost of adding it?',
      'An index speeds up lookups but uses storage and adds work when rows are inserted, updated or deleted.',
      ['lookup|search|read', 'storag|space', 'insert|updat|writ'],
    ],
    [
      'Networking',
      'What problem does DNS solve when you open a website?',
      'DNS resolves a domain name to an IP address so the client can locate the server.',
      ['domain|name', 'ip', 'resolv|map'],
    ],
    [
      'Operating Systems',
      'What is the difference between a process and a thread?',
      'A process has its own address space. Threads within a process share memory but have their own execution state.',
      ['process', 'thread', 'share', 'memory|address'],
    ],
    [
      'OOP',
      'Explain inheritance using a base class and a derived class.',
      'A derived class inherits fields or methods from a base class and can extend or override behavior.',
      ['base|parent', 'derived|child', 'method|behavior', 'inherit|reus'],
    ],
    [
      'APIs',
      'What does an HTTP 404 response mean?',
      'The server could not find the requested resource.',
      ['resource|page', 'not found|could not find|missing'],
    ],
    [
      'Security',
      'How do authentication and authorization differ?',
      'Authentication verifies who a user is. Authorization determines which resources or actions that user can access.',
      ['identity|who|verif', 'permission|access|allow'],
    ],
    [
      'Git',
      'Why might a team use a separate Git branch for a new feature?',
      'A branch isolates feature changes so the team can review and test them before merging into the shared branch.',
      ['isolat|separat', 'review|test', 'merge'],
    ],
    [
      'Testing',
      'What is the difference between a unit test and an integration test?',
      'A unit test checks a small component in isolation. An integration test checks interactions between components.',
      ['isolat|small', 'interact|together', 'component'],
    ],
    [
      'Concurrency',
      'What is a race condition? Give one way to prevent it.',
      'A race condition occurs when concurrent operations on shared state depend on timing. A lock or atomic operation can protect the state.',
      ['concurrent|simultaneous', 'shared', 'lock|atomic|mutex'],
    ],
  ],
  DSA: [
    [
      'Queues',
      'How does a queue remove items, and where would you use one?',
      'A queue removes items in first-in-first-out order. It can represent jobs waiting for processing.',
      ['first|fifo', 'job|task|wait'],
    ],
    [
      'Stacks',
      'How can a stack check whether parentheses are balanced?',
      'Push opening parentheses. For a closing parenthesis, pop a matching opening one. Reject unmatched closes and require an empty stack at the end.',
      ['push', 'pop', 'empty|unmatched'],
    ],
    [
      'Binary Search',
      'Why must ordinary binary search operate on sorted data?',
      'Sorted order lets a comparison eliminate one half of the search range without losing the target.',
      ['sort|order', 'half', 'compar'],
    ],
    [
      'Hash Tables',
      'What is a hash collision, and how can chaining handle it?',
      'A collision occurs when different keys map to the same bucket. Chaining stores multiple entries in that bucket, often in a linked list.',
      ['same', 'bucket|index', 'list|multiple'],
    ],
    [
      'Trees',
      'What is the maximum number of children of one node in a binary tree?',
      'A binary tree node has at most two children, commonly called left and right.',
      ['two|2', 'child'],
    ],
    [
      'Graphs',
      'When can breadth-first search find a shortest path?',
      'Breadth-first search finds shortest paths by edge count in an unweighted graph by exploring one level at a time.',
      ['unweighted|equal weight', 'level', 'edge|path'],
    ],
    [
      'Sorting',
      'Why can merge sort require extra memory?',
      'Merging sorted subarrays commonly uses a temporary array, requiring linear auxiliary space.',
      ['merg', 'temporary|extra|auxiliary', 'linear|o(n)'],
    ],
    [
      'Recursion',
      'What happens if a recursive function never reaches a base case?',
      'Calls keep adding stack frames until execution fails, often with a stack overflow.',
      ['stack', 'overflow|exhaust|fail', 'call'],
    ],
    [
      'Two Pointers',
      'How can two pointers check whether a string is a palindrome?',
      'Compare characters from the left and right ends and move both pointers inward. A mismatch means it is not a palindrome.',
      ['left', 'right', 'compar|match', 'inward|middle'],
    ],
    [
      'Complexity',
      'What is the time complexity of two nested loops that each run n times?',
      'The loops perform n multiplied by n iterations, giving quadratic O(n squared) time.',
      ['quadratic|n squared|n^2|n*n|n2'],
    ],
  ],
  HR: [
    [
      'Teamwork',
      'How would you handle a teammate missing a deadline that affects your task?',
      'Discuss the blocker privately, agree on a revised plan, and communicate the impact early. Offer help while keeping responsibilities clear.',
      ['discuss|talk|communicat', 'block|reason', 'plan|deadline', 'help|support'],
    ],
    [
      'Learning',
      'Describe how you would learn an unfamiliar tool for your first assignment.',
      'Clarify the task, read the documentation, build a small example, and ask focused questions when blocked.',
      ['task|requirement', 'document', 'example|practice', 'ask|question'],
    ],
    [
      'Feedback',
      'How would you respond to feedback that your presentation was unclear?',
      'Ask for specific examples, acknowledge the feedback, and revise the presentation with a clearer structure before practising again.',
      ['specific|example', 'feedback', 'revis|improv|practi'],
    ],
    [
      'Priorities',
      'What would you do if two managers gave you urgent tasks at the same time?',
      'Explain the conflicting deadlines, clarify priority and impact with both managers, and agree on a realistic schedule.',
      ['deadline|urgent', 'priorit', 'clarif|discuss|agree'],
    ],
    [
      'Ownership',
      'What would you do after finding a mistake in work you already submitted?',
      'Inform the relevant person promptly, explain the impact, correct the mistake, and add a check to avoid repeating it.',
      ['inform|tell|communicat', 'correct|fix', 'check|prevent'],
    ],
    [
      'Communication',
      'How would you explain a technical issue to someone without a technical background?',
      'Use plain language and a relevant example, explain the impact, and check that the other person understands.',
      ['plain|simple', 'example', 'impact', 'understand'],
    ],
    [
      'Planning',
      'How do you make a large assignment easier to complete?',
      'Break it into smaller tasks, estimate effort, identify dependencies, and set milestones to track progress.',
      ['small|break', 'estimat', 'depend', 'milestone|progress'],
    ],
    [
      'Integrity',
      'What would you do if asked to report a task as complete before it was tested?',
      'Explain what is complete and what remains untested, describe the risk, and agree on time to finish verification.',
      ['untested|test', 'risk', 'explain|honest', 'time|verif'],
    ],
    [
      'Conflict',
      'How would you discuss two different technical approaches with a teammate?',
      'Agree on requirements, compare the tradeoffs using evidence, and test a small example if needed before deciding together.',
      ['requirement', 'tradeoff|trade-off|compar', 'evidence|test', 'together|agree'],
    ],
    [
      'Growth',
      'How would you turn a rejected internship application into a useful learning experience?',
      'Review the requirements and your preparation, request feedback if available, identify a skill gap, and make a practice plan.',
      ['review', 'feedback', 'skill|gap', 'plan|practice'],
    ],
  ],
  Aptitude: [
    ['Percentages', 'What is 25% of 360? Enter only the number.', '90', ['90']],
    ['Averages', 'Find the average of 8, 14 and 20. Enter only the number.', '14', ['14']],
    [
      'Ratios',
      'There are 18 boys and 12 girls. Give the ratio of boys to girls in simplest form, using a colon.',
      '3:2',
      ['3:2'],
    ],
    [
      'Time Speed Distance',
      'A train travels at 60 km/h for 2.5 hours. How many kilometres does it travel? Enter only the number.',
      '150',
      ['150'],
    ],
    [
      'Profit and Loss',
      'An item costs 500 rupees and sells for 600 rupees. What is the profit percentage? Enter only the number.',
      '20',
      ['20'],
    ],
    [
      'Simple Interest',
      'Find simple interest on 2000 rupees at 6% per year for 3 years. Enter only the number.',
      '360',
      ['360'],
    ],
    [
      'Probability',
      'A fair six-sided die is rolled once. Give the probability of an even number as a simplified fraction.',
      '1/2',
      ['1/2'],
    ],
    [
      'Time and Work',
      'Four equally fast workers finish a task in 9 days. How many days would six workers need? Enter only the number.',
      '6',
      ['6'],
    ],
    [
      'Discounts',
      'A 1200-rupee bag has a 15% discount. What is the sale price in rupees? Enter only the number.',
      '1020',
      ['1020'],
    ],
    ['Equations', 'Solve 3x + 7 = 31. Enter only the value of x.', '8', ['8']],
  ],
  'Logical Reasoning': [
    [
      'Number Series',
      'Complete the series: 5, 10, 20, 40, __. Enter only the number.',
      '80',
      ['80'],
    ],
    [
      'Number Series',
      'Complete the square-number series: 1, 4, 9, 16, __. Enter only the number.',
      '25',
      ['25'],
    ],
    [
      'Directions',
      'You face north and turn right twice. Which direction do you face? Enter one word.',
      'south',
      ['south'],
    ],
    [
      'Ordering',
      'Mira is taller than Dev. Dev is taller than Sam. Who is shortest? Enter the name.',
      'sam',
      ['sam'],
    ],
    [
      'Syllogisms',
      'All squares are rectangles. Must every rectangle be a square? Answer yes or no.',
      'no',
      ['no'],
    ],
    [
      'Odd One Out',
      'Which number is not prime: 2, 3, 5, 9, 11? Enter only the number.',
      '9',
      ['9'],
    ],
    ['Letter Series', 'Complete the sequence: A, C, E, G, __. Enter one letter.', 'i', ['i']],
    [
      'Calendar',
      'Today is Monday. What day will it be 10 days from today? Enter the weekday.',
      'thursday',
      ['thursday'],
    ],
    [
      'Relationships',
      'Ravi is the brother of Sita. Sita is the mother of Anu. What is Ravi to Anu? Enter one word.',
      'uncle',
      ['uncle'],
    ],
    [
      'Ordering',
      'In a race, you overtake the runner in second place. What position are you now in? Enter 1, 2 or 3.',
      '2',
      ['2'],
    ],
  ],
  Verbal: [
    [
      'Grammar',
      'Choose the correct verb: She ___ to college every day. (go/goes)',
      'goes',
      ['goes'],
    ],
    [
      'Grammar',
      'Choose the correct word: There are ___ books on the shelf. (much/many)',
      'many',
      ['many'],
    ],
    [
      'Vocabulary',
      'Choose the opposite of scarce: rare, abundant, tiny. Enter one word.',
      'abundant',
      ['abundant'],
    ],
    [
      'Vocabulary',
      'Choose a synonym of rapid: slow, swift, late. Enter one word.',
      'swift',
      ['swift'],
    ],
    [
      'Prepositions',
      'Complete the sentence: The meeting starts ___ 9 am. (at/in/on)',
      'at',
      ['at'],
    ],
    [
      'Grammar',
      'Choose the correct past tense: Yesterday we ___ a movie. (see/saw/seen)',
      'saw',
      ['saw'],
    ],
    ['Articles', 'Choose the article: He studies at ___ university. (a/an)', 'a', ['a']],
    [
      'Agreement',
      'Choose the correct verb: The list of items ___ on the desk. (is/are)',
      'is',
      ['is'],
    ],
    [
      'Spelling',
      'Choose the correctly spelled word: recieve, receive. Enter the correct word.',
      'receive',
      ['receive'],
    ],
    [
      'Vocabulary',
      'Choose the opposite of expand: extend, contract, increase. Enter one word.',
      'contract',
      ['contract'],
    ],
  ],
};
